-- AUTO-GENERATED by scripts/update_bench_tables.sh — do not edit
module ChartData where

-- DGEMM comparison (4 threads)
dgemmLabels :: [String]
dgemmLabels = ["N=128", "N=256", "N=512", "N=1024"]
dgemmData :: [[Double]]
dgemmData = [[0.64, 0.77], [9.47, 10.22], [66.11, 68.05], [603.84, 536.88]]

-- Crossover
crossoverLabels :: [String]
crossoverLabels = ["100", "200", "500", "1K", "5K", "100K"]
crossoverSeq, crossoverPar :: [Double]
crossoverSeq = [0.5, 1.3, 3.6, 7.5, 48.1, 1100.9]
crossoverPar = [2.1, 2.2, 2.9, 3.8, 16.5, 290.0]

-- FFI overhead
ffiData :: [[Double]]
ffiData = [[0.0], [2.3], [66.6]]

-- Batched calls
batchedLabels :: [String]
batchedLabels = ["1", "2", "5", "10", "20", "50", "100"]
batchedCmm, batchedSafe :: [Double]
batchedCmm = [68.9, 35.9, 15.4, 8.8, 5.3, 3.4, 2.7]
batchedSafe = [70.7, 72.3, 71.2, 70.7, 71.7, 71.3, 71.1]
